import { Link } from 'react-router-dom';

const sections=[
  {title:'Why this exists',paragraphs:[
    'A tokenized stock can keep trading after the underlying exchange closes. During that closure, a token quote is a price in its own market; it is not an observed transaction in the underlying share. The last official close remains a useful anchor, but it cannot incorporate information that arrives later.',
    'Kairos asks how far that anchor should move when the wider market, sector peers and observable news change. It then compares the estimate with the token price. The difference is a question to investigate, not an arbitrage guarantee: trading costs, custody, redemption and liquidity can prevent a gap from being captured.',
    'Auto mode uses Bitget quotes and measured underlying daily history when a coherent, current real-data bundle is available. If it is unavailable, the whole market view falls back to labelled simulation. The Record remains the separately labelled synthetic ledger; its figures are not evidence of real-market performance. Regular and extended sessions already have external price discovery, so reckoning pauses then. Friday from the official close until 20:00 New York, zero drift and a bid/ask band are intentional. On half-days the official close is 13:00; the extended session still ends at 20:00.'],},
  {title:'What we compute',formula:'fair = anchor × exp(β·market + γ·sector + news)',paragraphs:[
    'The reckoning starts with the underlying’s last official regular-session close. The market term is the index token’s log return since that close, multiplied by the instrument’s gap beta. The sector term is the median market-adjusted return of other names in the same sector, multiplied by the sector loading. The instrument itself is excluded; a sector with no other members contributes nothing.',
    'News is an estimated log-return impact for relevant headlines after the anchor. Known impacts are summed and dampened as 0.10 × tanh(sum / 0.10), so repeated stories cannot make that term grow without bound. An unknown impact remains unknown, not a confident zero. Synthetic headlines have handwritten impacts; optional language providers classify real headlines outside the browser.',
    'Drift is ln(token price / fair). Positive means the token is rich relative to this model; negative means cheap. Displayed returns use 100 × (exp(log return) − 1). When the exchange is not dark, fair equals the token price and drift is zero. The band uses the observed bid and ask, with a small guarded fallback if those quotes are unavailable.'],},
  {title:'Why gap beta',formula:'ln(openᵢ / previous closeᵢ) = α + β·ln(openₘ / previous closeₘ) + residual',paragraphs:[
    'Close-to-close beta mixes the response to overnight information with an entire day of trading. Our target is a different event: the first official price after a closure. We therefore regress the underlying’s overnight gaps on its index factor’s overnight gaps over the latest 250 matched trading sessions.',
    'The regression estimates an intercept, but the reckoning uses only its slope and slope uncertainty. Carrying an estimated average overnight drift into every closure would imply a persistent edge that this sample cannot establish. Gap beta can differ from an intraday or close-to-close beta; we do not assume a fixed relationship between them.',
    'After removing the market component, another regression estimates the loading on leave-one-out sector residuals. Their median reduces the influence of an unusual peer. The remaining residual standard deviation supplies the idiosyncratic uncertainty. Real-data estimates use 250 matched official sessions. Demo mode retains its separate simulated history.',
    'Our live validation caught unstable overnight-gap estimates for AAPL and MSFT in the 23 September 2025 to 21 September 2026 sample. AAPL had full beta 0.087 (t = 1.307); its first and last 125-session estimates were 0.430 and -0.103. MSFT had full beta 0.384 (t = 3.798), but the halves fell from 0.722 to 0.185, with second-half t = 1.266. Neither held up under our split-sample stability check. We retain the measured estimates, widen their uncertainty bands by 20%, and exclude them from featured examples. This is what a live validation process should catch and disclose, rather than hide.',
    'The same rule also flags NFLX, META and PLTR. Stable requires full-sample and both half-sample absolute t-statistics of at least 2, matching nonzero signs, and half-sample slopes within a factor of two. The full ranking is reviewed for sector coherence; broad semiconductors and volatile single names rank above most defensive large names in this sample. SPY and QQQ are self-factor identities, not independent significance evidence. These are screening rules, not proof of future accuracy. Overnight-gap beta need not resemble an intraday beta, especially in large indexed names'],},
  {title:'Why the band is not a line',formula:'band = fair × exp(±1.2816·σ)',paragraphs:[
    'The nominal central 80% reckoning band combines four variance terms: beta-estimation error applied to the market move, elapsed idiosyncratic variance, news uncertainty, and a liquidity penalty. The last term is [0.6 × (1 − trust) × sigmaIdio]². Adding these terms assumes their errors are independent; a common shock can violate that assumption.',
    'Elapsed uncertainty uses session-equivalent hours rather than treating every hour alike. Weekend hours weigh 0.12, weekday overnight hours 0.25, extended hours 0.45, and would-be regular weekday hours 1.00, including a weekday holiday. The engine integrates in quarter-hour steps and divides by the standard overnight total of 6.275 equivalent hours. It measures from the official close, even though darkness begins later.',
    'The combined log-return standard deviation is clamped between 0.0015 and 0.15; parameters older than fourteen days or flagged unstable widen it by 20%, applied once even when both conditions hold. The same safeguard widens the opening-gap forecast interval without moving its median. News uncertainty is half the absolute dampened impact times one minus mean confidence, with a 0.002 floor whenever relevant news exists. These safeguards prevent false precision; they cannot make an incorrectly specified model calibrated.',
    'This is a model interval, not a loss boundary. The Record measures the opening-gap forecast interval separately. Its current synthetic backtest covers about 60.9% of outcomes, below the nominal 80% target. Further tuning is deferred until real historical data is available.'],diagram:'weights'},
  {title:'How we score trust',formula:'trust = 0.45·volume score + 0.20·spread score + 0.35·efficiency score',paragraphs:[
    'Trust measures how much information the observed trading supports. Volume since the close is compared with the historical median for the same kind of closure and hour within that window. The volume score is log(1 + volume ratio) / log(3), clamped to the interval from zero to one.',
    'A quoted spread of five basis points earns the full spread score; fifty basis points earns none, with a linear scale between them. A missing spread contributes a neutral half-score. Efficiency divides the volume ratio by max(|total log return| / 0.01, 1), then applies the same logarithmic scoring rule. A large move therefore needs more volume than a small move to earn the same trust.',
    'Scores below 0.33 are thin, below 0.66 moderate, and otherwise deep. Zero observed volume behind a nonzero move forces trust to zero. Missing volume is treated conservatively and disclosed. This is not measured order-book depth, nor a probability that the forecast is right.'],},
  {title:'What “unaccounted” means, and what it does not',formula:'unaccounted = total log return − market − sector − news',paragraphs:[
    'The decomposition is an accounting identity. The components sum to the token’s move from the official close; the leftover is whatever the selected factors and supplied news do not explain. Explained share is 1 − |unaccounted| / |total|, clamped between zero and one. For a nearly zero total return the engine reports full explained share by convention, not because a flat tape proves the model correct.',
    'An unexplained move with thin trading may be a fragile print. An unexplained move with substantial volume is more interesting: someone may be acting on information outside our feed, or the factor model may be wrong. Kairos does not equate unexplained with fake. Neither case establishes a direction for an order.'],},
  {title:'How the forecast works',formula:'gap median = (1 − w)·(−κ·drift) + w·analog median; w = min(count / 60, 0.5)',paragraphs:[
    'The target is ln(next official open / current token price), the gap a token holder would face at the bell. The model term is minus kappa times current drift. Kappa is the negative fitted slope of historical gap on drift, clamped between zero and one, estimated separately for thin, moderate and deep liquidity. Fewer than forty instrument observations trigger pooling within the sector.',
    'Forecast sigma is measured around the actual intercept-free, clamped predictor: sqrt(sum((realised gap + kappa × drift)²) / (n − 1)), with a minimum of 0.0015. This includes prediction bias that would disappear if we measured only centered regression residuals. Degenerate or very small samples use conservative defaults and carry low-evidence labels. The initial real-data path has no calibrated token reversion history: kappa is zero and sigmaForecast is 0.03, with zero fitted reversion observations and no real analogs. This is a conservative cold start, not a validated predictive edge. Synthetic fits are never substituted into the real-data path.',
    'Weighted nearest neighbours compare drift magnitude, explained share, trust, elapsed window progress and volatility regime, with penalties for different sectors, closure types and news categories. Outcomes are sign-flipped when a neighbour’s drift points the other way. The analog median and quantiles use distance weights; sample count does not mean independent events, since a window supplies several observations.',
    'Analogs contribute at most half the forecast because a small, selected sample should not overwhelm the model. Combined sigma is sqrt((1 − w)² × modelSigma² + w² × analogSigma²), floored at 0.0015. The forecast interval is median ± 1.2816 × sigma; the probability of opening below the token price is Φ(−median / sigma). Fewer than ten analogs or forty parameter observations halves the confidence multiplier and raises an evidence warning.'],},
  {title:'How the record is kept',paragraphs:[
    'Automatic fixes are logged only while the exchange is dark and absolute log drift exceeds 0.004, approximately a 0.4% price difference. A usable forecast is required. The threshold avoids filling the record with essentially unchanged quotes; it also means the record grades selected dislocations, not every market moment. The same instrument, official-close anchor and UTC hour cannot generate duplicate automatic fixes.',
    'Each fix retains its original forecast, timestamp, model version and input hash. Resolution waits for the target official open and compares that opening price with the saved token price. A split or special dividend between logging and the target bell voids the fix. Voids remain visible but do not enter statistics. An input hash aids auditability; it is not a cryptographic guarantee that the repository was never edited.',
    'Backtest fixes reconstruct earlier windows using information available at their anchors and analog outcomes resolved before those anchors. Their token paths are synthetic, not recovered historical trades. The forward ledger logs as time advances, but its prices are also synthetic today. We keep these origins separate; the label “live” describes logging origin, not proof of real-market data.',
    'Skill is 1 − model squared error / unchanged-price baseline squared error. Zero adds nothing; negative is worse than the baseline. Coverage counts realised gaps inside the saved forecast interval. A directional hit requires the forecast and realised gap to share a sign and the forecast magnitude to exceed 0.001. Empty samples and a zero-variance baseline use explicit zero conventions, so sample counts must be read alongside scores.'],diagram:'record'},
  {title:'What we cannot see',paragraphs:[
    'Kairos does not observe full order-book depth, hidden liquidity, trader positioning, options prices, dealer hedging, off-feed news, or whether apparently separate stories describe the same event. Volume and quoted spread are proxies, not a view into participant intent. A language model’s news-impact estimate is a judgement, not a measured causal effect.',
    'The model does not price issuer failure, custody loss, redemption restrictions, jurisdictional access, fees, execution slippage or the ability to trade the underlying at the opening print. It has no user portfolio, tax circumstances or risk tolerance. Research therefore supplies no justified nonzero account allocation and never places orders.',
    'Normal-distribution bands can miss jumps and correlated shocks. Parameters can go stale, synthetic scenarios can manufacture apparent skill, and multiple samples from the same window can overstate effective evidence. The browser’s analog query currently uses a neutral volatility regime, while pipeline sampling uses a trailing historical regime. The exchange calendar is maintained only through 2027. These are implementation limits, not resolved research questions.'],},
  {title:'What would change our mind',paragraphs:[
    'A sustained negative skill score on genuinely forward, real-data fixes would mean this model is worse than simply accepting the token price. Coverage persistently below 70% would reject the nominal 80% interval as a useful description of uncertainty. If thin, moderate and deep buckets show no meaningful difference in skill or reversion, the liquidity-based thesis would lack supporting evidence.',
    'The present synthetic coverage is already below that threshold. It establishes a limitation of this simulation, not an answer about real-market performance. We will not tune more aggressively against engineered scenarios to make the displayed number look better. The next assessment belongs to real historical data and then a sufficiently varied forward record, with overlapping windows treated as dependent observations.',
    'Failure would be published, not hidden by pooling ledgers, selecting a favourable period or discarding misses. Any change to a formula requires a new model version and a new, separately interpretable record. Until evidence improves, the estimate is a research aid with explicit uncertainty.'],},
];
export function MethodContent({onNavigate}:{onNavigate:()=>void}){return <section aria-labelledby="method-content-title" className="guide-panel">
  <h2 id="method-content-title">Method & limitations</h2><p>The assumptions, equations and tests behind the estimate. Model 1.2.0 safeguards; existing saved fixes retain their original versions.</p>
  {sections.map((section,index)=><details key={section.title} className="py-4 border-t border-rule">
    <summary className="cursor-pointer"><strong>{index+1}. {section.title}</strong></summary>
    <div className="grid gap-4 pt-4" style={{maxWidth:'68ch'}}>{section.formula&&<p style={{overflowWrap:'anywhere'}}><code>{section.formula}</code></p>}{section.paragraphs.map(p=><p key={p}>{p}</p>)}
      {section.diagram==='weights'&&<figure><svg viewBox="0 0 480 135" role="img" aria-label="Session weights: weekend 0.12, weekday overnight 0.25, extended 0.45, regular weekday 1.00"><path d="M10 100H125V87H240V67H355V12H470" fill="none" stroke="var(--brass)" strokeWidth="2"/><g fill="currentColor" fontSize="11"><text x="10" y="123">Weekend 0.12</text><text x="128" y="123">Night 0.25</text><text x="244" y="123">Extended 0.45</text><text x="361" y="123">Regular 1.00</text></g></svg><figcaption className="micro-note">Relative uncertainty weight per hour, not a chronological price path.</figcaption></figure>}
      {section.diagram==='record'&&<figure><svg viewBox="0 0 480 85" role="img" aria-label="A saved forecast is compared with the official open, then scored within its own ledger"><path d="M20 35H460" stroke="var(--rule-strong)"/><g fill="var(--brass)"><circle cx="30" cy="35" r="4"/><circle cx="240" cy="35" r="4"/><circle cx="450" cy="35" r="4"/></g><g fill="currentColor" fontSize="12"><text x="10" y="65">Save the fix</text><text x="196" y="65">Observe open</text><text x="384" y="65">Score the gap</text></g></svg><figcaption className="micro-note">Backtest and forward fixes follow the same scoring rules, in separate ledgers.</figcaption></figure>}
    </div></details>)}<p className="pt-4"><Link to="/record" onClick={onNavigate}>Read the forecast record</Link></p>
</section>;}
