import { useEffect,useState } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { alignedGap } from '@engine/analogs';
import { attributionSentence } from '@engine/attribute';
import { buildFix,MODEL_VERSION } from '@engine/score';
import type { Fix } from '@engine/types';
import { useDesk } from '@/data/queries';
import { useHistory } from '@/hooks/useHistory';
import { pct,price,share,time as timeNY,sectorName } from '@/lib/format';
import { AnalogStrip,ForecastCone,ReckoningChart,Waterfall } from '@/components/charts/InstrumentCharts';
import { Boundary,Button,Field,Loading,Notice,Panel,Table,Tag } from '@/components/primitives';

export default function Instrument(){
 const {symbol='rNVDA'}=useParams(),navigate=useNavigate(),{data,board,loading,error,retry,fallbacks}=useDesk();
 const row=board.rows.find(r=>r.instrument.symbol===symbol),history=useHistory(data,board,symbol),[confirmation,setConfirmation]=useState(''),[all,setAll]=useState(false);
 useEffect(()=>{setConfirmation('');setAll(false);},[symbol]);
 if(!row)return <div className="empty"><h1>Instrument unavailable</h1><p>{symbol} has no usable quote and anchor in this universe.</p><Link to="/">Return to the board</Link></div>;
 const r=row.reckoning,f=row.forecast,p=data.params.instruments[symbol]!,analogs=row.analogs,outcomes=analogs.neighbours.map(n=>alignedGap(n.record,r.drift));
 const news=board.news.filter(n=>n.ts>=board.session.anchorCloseTs&&n.ts<=board.ts&&(!n.symbols.length||n.symbols.includes(symbol))).sort((a,b)=>b.ts-a.ts),sources=new Set(news.map(n=>n.source)).size;
 const log=async()=>{if(!f)return;try{const fix=await buildFix({reckoning:r,forecast:f,session:board.session,modelVersion:MODEL_VERSION,origin:'live',loggedAt:board.ts});const stored=JSON.parse(localStorage.getItem('kairos.local-fixes')??'[]') as Fix[];localStorage.setItem('kairos.local-fixes',JSON.stringify([...stored.filter(v=>v.id!==fix.id),fix]));setConfirmation('Fix logged locally. The public record is written by the pipeline every hour.');}catch{setConfirmation('Local storage is unavailable. This fix was not saved.');}};
 return <article className="instrument-view"><header className="page-heading"><div><h1>{symbol} <span className="company-name">{row.instrument.name}</span></h1><p>{sectorName(row.instrument.sector)} · anchored to {row.instrument.anchorFactor}</p><span className="muted">Beta {p.beta.toFixed(2)} (±{p.betaStdErr.toFixed(2)}) · {p.nObs} observations</span></div><div className="instrument-actions"><Field label="Instrument"><select aria-label="Instrument" value={symbol} onChange={e=>navigate(`/instrument/${e.target.value}`)}>{data.universe.map(i=><option key={i.symbol}>{i.symbol}</option>)}</select></Field><Button variant="primary" disabled={!f||loading} onClick={()=>void log()}>Log a fix</Button></div></header>
 {confirmation&&<p role="status" className="notice">{confirmation}</p>}{error&&<Notice retry={retry}>{error} Showing the last available snapshot.</Notice>}{fallbacks.length>0&&<Notice>Using bundled synthetic data. All displayed evidence is simulated.</Notice>}
 {!board.session.isDark&&<Notice>Reckoning is paused during real price discovery. No dark-window forecast is issued.</Notice>}
 <div className="instrument-grid">
 <Panel title={!board.session.isDark?'Tracking the current quote':r.drift>=0?'Trading above reckoning':'Trading below reckoning'}><div className={`hero-drift ${Math.abs(r.drift)<.003?'tone-dim':r.drift>0?'tone-rust':'tone-verdigris'}`}>{pct(r.drift)}</div><dl className="facts"><div><dt>Traded</dt><dd>{price(r.tokenPrice)} USDT</dd></div><div><dt>Reckoned</dt><dd>{price(r.reckonedValue)} USDT</dd></div><div><dt>80% band</dt><dd>{price(r.bandLow)}–{price(r.bandHigh)}</dd></div></dl><Tag tone={r.trustLabel==='thin'?'amber':r.trustLabel==='deep'?'verdigris':'dim'}>{r.trustLabel} book</Tag><p className="trust-reasons">{row.liquidity.reasons.join('. ')+'.'}</p></Panel>
 <Panel title="Where this move came from"><Boundary name="Attribution"><Waterfall value={r.components}/></Boundary><p className="panel-prose">{attributionSentence(r.components,r.trust)}</p><p className="micro-note">Components add in log-return space, from the official close. Percentages are rounded.</p></Panel>
 <Panel title="Price against reckoning — this window" className="span-full"><Boundary name="Window history">{history?.error?<Notice>{history.error}</Notice>:history?.points.length?<ReckoningChart points={history.points} session={board.session} symbol={symbol}/>:<Loading label="window candles"/>}</Boundary><p className="micro-note">Hourly synthetic observations · grey area awaits the bell · arrow keys inspect the chart.</p></Panel>
 <Panel title="At the bell" className="soft">{f?<><Boundary name="Bell forecast"><ForecastCone forecast={f} outcomes={outcomes}/><AnalogStrip outcomes={outcomes} median={analogs.medianRealised} forecast={f.median}/></Boundary><p className="micro-note">Analog median {pct(analogs.medianRealised)} · forecast median {pct(f.median)}. Historical dots are aligned to today’s drift direction.</p><dl className="facts"><div><dt>Median</dt><dd>{pct(f.median)}</dd></div><div><dt>80% interval</dt><dd>{pct(f.p10)} to {pct(f.p90)}</dd></div><div><dt>Probability token falls</dt><dd>{share(f.pTokenFalls)}</dd></div><div><dt>Evidence</dt><dd>{f.analogCount} analogs</dd></div></dl><p className="micro-note">{row.evidence}</p><p className="micro-note">Forecast intervals have under-covered the synthetic backtest. <Link to="/record">Read the record</Link>.</p></>:<p className="muted">{loading?'Loading forecast evidence.':row.stale?'The quote is stale. A new forecast is withheld.':'No forecast is available for this session or model range.'}</p>}</Panel>
 <Panel title="What happened last time">{analogs.count?<><p className="panel-prose">{analogs.count} comparable situations. Median giveback {share(analogs.medianGivebackShare)}. Reverted toward reckoning in {share(analogs.revertedShare)}.</p><p className="micro-note">Synthetic history. Table outcomes retain their original signs.</p><Table label="Closest historical analogs"><thead><tr><th>Date / symbol</th><th className="numeric">Drift</th><th className="numeric">Outcome</th><th className="numeric">Distance</th></tr></thead><tbody>{analogs.neighbours.slice(0,all?analogs.count:6).map(n=><tr key={n.record.id}><td>{n.record.date}<small>{n.record.symbol}</small></td><td className="numeric">{pct(n.record.drift)}</td><td className="numeric">{pct(n.record.realisedGap)}</td><td className="numeric muted">{n.distance.toFixed(2)}</td></tr>)}</tbody></Table><Button variant="quiet" aria-expanded={all} onClick={()=>setAll(!all)}>{all?'Show closest six':`Show all ${analogs.count}`}</Button></>:<p className="muted">No comparable history is available yet.</p>}</Panel>
 <Panel title="What we can see"><ol className="news-timeline">{news.map(n=><li key={n.id}><div className="micro-note">{timeNY(n.ts)} NY · {new Date(n.ts).toISOString().slice(11,16)} UTC <Tag tone="amber">Synthetic</Tag></div><p>{n.headline}</p><div className="news-meta"><span>{n.source} · {n.category.replaceAll('_',' ')}</span><span>{n.impact===null?'Impact not estimated':n.impact===0?'No measurable impact':pct(n.impact)}</span></div></li>)}</ol>{!news.length&&<p className="muted">No news in our feed for this instrument during the window.</p>}</Panel>
 <Panel title="What we cannot see"><ul className="blind-spots"><li>Order book depth beyond the top of book.</li><li>Any news not in our feed. Our coverage is {sources} {sources===1?'source':'sources'} in this instrument’s window.</li><li>Positioning and flow. We see volume, not who traded.</li><li>Options market pricing{board.session.isDark?', which is closed too.':', which is not in this feed.'}</li>{p.nObs<60&&<li>Only {p.nObs} observations behind this instrument’s parameters. Treat the band as wide.</li>}</ul></Panel>
 </div></article>;
}
