import { useMemo, useState } from 'react';
import type { FixOrigin, SectorKey } from '@engine/types';
import { computeStats, SECTORS } from '@engine/score';
import { useDesk } from '@/data/queries';
import { filterLedger, signedScore, trustSentence, type LedgerFilter } from '@/lib/record';
import { sectorName } from '@/lib/format';
import { Boundary, Button, Field, Notice, Panel, Table, Tag } from '@/components/primitives';
import { CalibrationPlot } from '@/components/charts/CalibrationPlot';
import { RecordMetrics } from '@/components/domain/RecordMetrics';
import { FixRows } from '@/components/domain/FixRows';
export default function Record() {
    const { data, error, retry, fallbacks } = useDesk(), [origin, setOrigin] = useState<FixOrigin>('backtest'), [sector, setSector] = useState<SectorKey | 'all'>('all'), [trust, setTrust] = useState<LedgerFilter['trust']>('all'), [page, setPage] = useState(0);
    const sectors = useMemo(() => Object.fromEntries(data.universe.map(i => [i.symbol, i.sector])), [data.universe]);
    const live = useMemo(() => computeStats(data.ledgerLive, sectors), [data.ledgerLive, sectors]), backtest = useMemo(() => computeStats(data.ledgerBacktest, sectors), [data.ledgerBacktest, sectors]);
    const filtered = useMemo(() => filterLedger(origin === 'live' ? data.ledgerLive : data.ledgerBacktest, { origin, sector, trust }, sectors), [data, origin, sector, trust, sectors]), pending = filtered.filter(f => f.status === 'open'), resolved = filtered.filter(f => f.status !== 'open'), pages = Math.max(1, Math.ceil(resolved.length / 50)), activePage = Math.min(page, pages - 1), stats = origin === 'live' ? live : backtest;
    const download = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(filtered, null, 2)], { type: 'application/json' })), a = document.createElement('a'); a.href = url; a.download = `kairos-${origin}-${sector}-${trust}-synthetic.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
    return <article className="record-view"><header className="page-heading"><div><span className="eyebrow">[02] / ACCOUNTABILITY</span><h1>The record speaks.</h1><p>What we forecast. What actually happened.</p></div></header>
 <p className="record-disclosure">Simulated data. Forward and backtest results are always kept separate.</p>{error && <Notice retry={retry}>{error} Showing the available ledger artifacts.</Notice>}{fallbacks.length > 0 && <p className="micro-note">Bundled ledger artifacts are in use.</p>}
 <div className="record-comparison"><RecordMetrics stats={live} title="Live"/><RecordMetrics stats={backtest} title="Backtest"/></div>
 <section className="coverage-note"><div className="coverage-heading"><span className="coverage-indicator">!</span><div><h2>The bands need work.</h2><p>60.9% coverage against an 80% target at the September 20 checkpoint.</p></div></div><details><summary>Read the coverage audit</summary><p>The bounded audit found a forecast-error mismatch: uncertainty was estimated around an OLS fit with an intercept, but the shipped predictor discards that intercept and constrains reversion. Model 1.1.0 measures uncertainty around the predictor actually used. Coverage rose from 50.9% to 60.9%; the shortfall remains.</p><p>Every historical fixture window includes an engineered broad risk-off scenario, so there is no wholly quiet control. The separate 79.9% self-consistency test samples the forecast’s own Gaussian distribution; it does not validate coverage on this ledger. Existing forward fixes retain the model version recorded when logged.</p></details></section>
 <div className="ledger-controls"><Field label="Record"><select aria-label="Record origin" value={origin} onChange={e => { setOrigin(e.target.value as FixOrigin); setPage(0); }}><option value="live">Live</option><option value="backtest">Backtest</option></select></Field><Field label="Sector"><select aria-label="Sector" value={sector} onChange={e => { setSector(e.target.value as SectorKey | 'all'); setPage(0); }}><option value="all">All sectors</option>{SECTORS.map(s => <option key={s} value={s}>{sectorName(s)}</option>)}</select></Field><Field label="Trust"><select aria-label="Trust" value={trust} onChange={e => { setTrust(e.target.value as LedgerFilter['trust']); setPage(0); }}><option value="all">All trust</option><option value="thin">Thin</option><option value="moderate">Moderate</option><option value="deep">Deep</option></select></Field><Button onClick={download}>Download JSON</Button></div>
 <p className="micro-note">Charts describe the complete {origin === 'live' ? 'forward' : 'backtest'} record. Sector and trust filters apply to the ledger and download below.</p>
 <div className="record-analysis"><Panel title={`Calibration · ${origin === 'live' ? 'Live' : 'Backtest'}`}><Boundary name="Calibration">{stats.n ? <CalibrationPlot data={stats.calibration}/> : <p className="empty muted">No fixes have resolved yet. Calibration needs observed outcomes.</p>}</Boundary><p className="micro-note">Points on the diagonal mean stated probability matches observed frequency. Square size reflects sample count; the shaded 90% binomial band reflects sampling variation. It does not account for dependence between fixes.</p></Panel><Panel title={`Where the model has skill · ${origin === 'live' ? 'Live' : 'Backtest'}`}><Table label="Skill by trust"><thead><tr><th>Trust</th><th className="numeric">Skill</th><th className="numeric">n</th></tr></thead><tbody>{(['thin', 'moderate', 'deep'] as const).map(t => <tr key={t}><td>{t[0]!.toUpperCase() + t.slice(1)}</td><td className={`numeric ${stats.byTrust[t].n && stats.byTrust[t].skillScore < 0 ? 'tone-rust' : ''}`}>{stats.byTrust[t].n ? signedScore(stats.byTrust[t].skillScore) : '—'}</td><td className="numeric">{stats.byTrust[t].n}</td></tr>)}</tbody></Table><p className="panel-prose trust-conclusion">{trustSentence(stats)}</p></Panel></div>
 <section className="ledger-section"><h2>Awaiting the opening bell <span className="muted">({pending.length})</span></h2>{pending.length ? <FixRows fixes={pending} label="Open fixes"/> : <p className="empty muted">No open fixes match these filters.</p>}</section>
 <section className="ledger-section"><h2>The ledger <span className="muted">({resolved.length.toLocaleString()})</span></h2><p className="micro-note">Void fixes remain visible and are excluded from all statistics. All ledger times are UTC.</p>{resolved.length ? <FixRows fixes={resolved.slice(activePage * 50, (activePage + 1) * 50)} label="Resolved and void fixes"/> : <p className="empty muted">No resolved fixes match these filters. Pending predictions are shown above.</p>}<div className="pagination"><Button disabled={activePage === 0} onClick={() => setPage(activePage - 1)}>Previous</Button><span role="status">Page {activePage + 1} of {pages} · up to 50 rows</span><Button disabled={activePage >= pages - 1} onClick={() => setPage(activePage + 1)}>Next</Button></div></section>
 </article>;
}
