import {Fragment,useId,useState} from 'react';
import type {Fix} from '@engine/types';
import {trustLabel} from '@engine/liquidity';
import {pct,time} from '@/lib/format';
import {Button,Table,Tag} from '@/components/primitives';
export function FixRows({fixes,label}:{fixes:Fix[];label:string}){
 const [expanded,setExpanded]=useState<string|null>(null),prefix=useId();
 return <Table label={label}><thead><tr><th>Logged (UTC)</th><th>Symbol</th><th className="numeric">Drift</th><th className="numeric">Said</th><th className="numeric">80% band</th><th className="numeric">Happened</th><th>Result</th><th>Details</th></tr></thead><tbody>{fixes.map((f,i)=>{const open=expanded===f.id,detailId=`${prefix}-${i}`;return <Fragment key={f.id}><tr className={f.status==='void'?'fix-void':''} data-fix-id={f.id}><td>{time(f.loggedAt,'UTC','dd MMM yyyy')}<small>{time(f.loggedAt,'UTC','HH:mm')}</small></td><td>{f.symbol}<small>{f.origin==='live'?'Live':'Backtest'}</small></td><td className="numeric">{pct(f.drift)}</td><td className="numeric">{pct(f.forecast.median)}</td><td className="numeric">{pct(f.forecast.p10)}<small>to {pct(f.forecast.p90)}</small></td><td className="numeric">{f.realisedGap===null?'—':pct(f.realisedGap)}</td><td>{f.status==='void'?<Tag>Void</Tag>:f.status==='open'?<><span>Awaiting bell</span><small>{time(f.targetOpenTs,'UTC','dd MMM HH:mm')} UTC</small></>:<><span className={f.directionalHit?'tone-verdigris':'tone-rust'}>{f.directionalHit?'Hit':'Miss'}</span><small>{f.inBand?'In band':'Outside band'}</small></>}</td><td><Button variant="quiet" aria-expanded={open} aria-controls={detailId} aria-label={`${open?'Hide':'Show'} details for ${f.symbol}, ${new Date(f.loggedAt).toISOString()}`} onClick={()=>setExpanded(open?null:f.id)}>{open?'Hide':'View'}</Button></td></tr><tr className="fix-detail-row"><td colSpan={8}><div id={detailId} className={`fix-detail ${open?'expanded':''}`} aria-hidden={!open}><div><div className="fix-detail-inner">{open&&<><p>Model {f.modelVersion} · trust {f.trust.toFixed(4)} ({trustLabel(f.trust)})</p><p className="input-hash">Input hash: {f.inputsHash}</p><p className="micro-note">The original volume, spread, and efficiency breakdown was not retained in this fix’s schema. It cannot be reconstructed reliably from a current quote.</p><pre>{JSON.stringify(f,null,2)}</pre></>}</div></div></div></td></tr></Fragment>;})}</tbody></Table>;
}
